import pyautogui as root
from time import sleep
#print(root.position())
root.moveTo(129,1062,1)
root.click(clicks=1,interval =0.25,button='left')
root.press('c')
root.press('h')
root.press('r')
root.press('o')
root.press('m')
root.press('e')
#root.moveTo(104,512,1)
#root.click(clicks=1,interval =0.25,button='left')
root.press('enter')
#root.moveTo(753,460,1)
#root.click(clicks=1,interval =0.25,button='left')
root.moveTo(923,47,1)
root.press('s')
root.press('t')
root.press('e')
root.press('a')
root.press('m')
root.press('enter')
root.moveTo(378,295,1)
root.click(clicks=1,interval =0.25,button='left')
root.moveTo(1231,88,1)
root.click(clicks=1,interval =0.25,button='left')
root.moveTo(605,562,1)
root.click(clicks=1,interval =0.25,button='left')